# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'row.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import tensorflow as tf
# import matplotlib.pyplot as plt
import tensorflow_hub as hub
import os
import cv2
import numpy as np
from tqdm.notebook import tqdm
print(tf.config.list_physical_devices('GPU'))