# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'predict.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
current_directory = os.path.dirname(os.path.abspath(__file__)) + '\\'


from PyQt5 import QtCore, QtGui, QtWidgets


class Predict(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 766)
        MainWindow.setMaximumSize(QtCore.QSize(2086, 2788))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("#widget_3{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(95, 153, 207, 255), stop:1 rgba(0, 133, 255, 255));\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setStyleSheet("#widget_2{\n"
"background-color: rgba(32, 255, 51, 0);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom : 1px solid rgb(0, 85, 127)}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_9 = QtWidgets.QWidget(self.widget_5)
        self.widget_9.setMinimumSize(QtCore.QSize(100, 50))
        self.widget_9.setMaximumSize(QtCore.QSize(100, 50))
        self.widget_9.setStyleSheet("#widget9{border-right : 2px solid rgb(125, 145, 170);}")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.widget_9)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setStyleSheet("\n"
"border-radius : 10px")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(current_directory + "Image/Fox.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.horizontalLayout_4.addWidget(self.widget_9)
        spacerItem = QtWidgets.QSpacerItem(1013, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_substract = QtWidgets.QPushButton(self.widget_4)
        self.btn_substract.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_substract.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_substract.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-color:rgba(255,255,255,0);box-shadow:0,0,0,0}\n"
"#btn_substract:hover{\n"
"background-color:rgb(0,160,255);\n"
"\n"
"\n"
"")
        self.btn_substract.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(current_directory + "Image/icons8-reduce-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_substract.setIcon(icon)
        self.btn_substract.setIconSize(QtCore.QSize(42, 29))
        self.btn_substract.setObjectName("btn_substract")
        self.horizontalLayout_3.addWidget(self.btn_substract)
        self.btn_pile_stack = QtWidgets.QPushButton(self.widget_4)
        self.btn_pile_stack.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_pile_stack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pile_stack.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-color:rgba(255,255,255,0);box-shadow:0,0,0,0}\n"
"#btn_pile_stack:hover{\n"
"background-color:rgb(0,160,255);\n"
"")
        self.btn_pile_stack.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(current_directory + "Image/icons8-restore-window-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pile_stack.setIcon(icon1)
        self.btn_pile_stack.setIconSize(QtCore.QSize(23, 27))
        self.btn_pile_stack.setObjectName("btn_pile_stack")
        self.horizontalLayout_3.addWidget(self.btn_pile_stack)
        self.btn_exit = QtWidgets.QPushButton(self.widget_4)
        self.btn_exit.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exit.setStyleSheet("#btn_exit{background-color: rgba(255, 255, 255, 0);\n"
"background-color:rgba(255,255,255,0);\n"
"}\n"
"#btn_exit:hover{\n"
"background-color: rgb(0,160,255);\n"
"border-top-right-radius: 10px;\n"
"}")
        self.btn_exit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(current_directory + "Image/icons8-close-window-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon2)
        self.btn_exit.setIconSize(QtCore.QSize(20, 28))
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout_3.addWidget(self.btn_exit)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_creen = QtWidgets.QLabel(self.widget_6)
        self.label_creen.setMaximumSize(QtCore.QSize(900, 512))
        self.label_creen.setStyleSheet("border-top-right-radius: 20px;")
        self.label_creen.setText("")
        self.label_creen.setPixmap(QtGui.QPixmap("Image/z5461290588979_692bf1a21a79b202b016a475ef95d80d.jpg"))
        self.label_creen.setScaledContents(True)
        self.label_creen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_creen.setObjectName("label_creen")
        self.verticalLayout_2.addWidget(self.label_creen)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.text_predict = QtWidgets.QLineEdit(self.widget_6)
        self.text_predict.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text_predict.setFont(font)
        self.text_predict.setStyleSheet("border-radius: 15px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"")
        self.text_predict.setObjectName("text_predict")
        self.verticalLayout_2.addWidget(self.text_predict)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_8.addWidget(self.widget_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Predict()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
