# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bxh.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget____ = QtWidgets.QWidget(self.centralwidget)
        self.widget____.setObjectName("widget____")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget____)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label___33 = QtWidgets.QLabel(self.widget____)
        self.label___33.setAlignment(QtCore.Qt.AlignCenter)
        self.label___33.setObjectName("label___33")
        self.horizontalLayout_22.addWidget(self.label___33)
        self.label___5 = QtWidgets.QLabel(self.widget____)
        self.label___5.setText("")
        self.label___5.setPixmap(QtGui.QPixmap("Image/image 2.png"))
        self.label___5.setScaledContents(True)
        self.label___5.setAlignment(QtCore.Qt.AlignCenter)
        self.label___5.setObjectName("label___5")
        self.horizontalLayout_22.addWidget(self.label___5)
        self.label___1 = QtWidgets.QLabel(self.widget____)
        self.label___1.setText("")
        self.label___1.setPixmap(QtGui.QPixmap("Image/Ellipse 10.png"))
        self.label___1.setScaledContents(True)
        self.label___1.setAlignment(QtCore.Qt.AlignCenter)
        self.label___1.setObjectName("label___1")
        self.horizontalLayout_22.addWidget(self.label___1)
        self.label___44 = QtWidgets.QLabel(self.widget____)
        self.label___44.setAlignment(QtCore.Qt.AlignCenter)
        self.label___44.setObjectName("label___44")
        self.horizontalLayout_22.addWidget(self.label___44)
        self.label___2 = QtWidgets.QLabel(self.widget____)
        self.label___2.setAlignment(QtCore.Qt.AlignCenter)
        self.label___2.setObjectName("label___2")
        self.horizontalLayout_22.addWidget(self.label___2)
        self.horizontalLayout.addWidget(self.widget____)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label___33.setText(_translate("MainWindow", "1"))
        self.label___44.setText(_translate("MainWindow", "Pham Doan Minh Hieu"))
        self.label___2.setText(_translate("MainWindow", "100"))
