# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("#widget{\n"
"    background-color: qlineargradient(x1: 0, x2: 1,stop: 0 rgb(23, 42, 162), stop: 0.40 rgb(50, 140, 199),stop:0.60 rgb(50, 140, 199),stop: 1 rgb(23, 42, 162));\n"
"    border-top-left-radius: 150px;  \n"
"     border-bottom-right-radius: 150px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_2.setObjectName("widget_2")
        self.btn_exit = QtWidgets.QPushButton(self.widget_2)
        self.btn_exit.setGeometry(QtCore.QRect(460, 0, 35, 28))
        self.btn_exit.setStyleSheet("#btn_exit{background-color: rgba(255, 255, 255, 10)}\n"
"#btn_exit:hover{\n"
"background-color : rgb(0, 0, 127)\n"
"}")
        self.btn_exit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setMinimumSize(QtCore.QSize(400, 40))
        self.stackedWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.page_1)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color :rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.LEdit_email_signin = QtWidgets.QLineEdit(self.page_1)
        self.LEdit_email_signin.setMinimumSize(QtCore.QSize(0, 40))
        self.LEdit_email_signin.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px ;\n"
"color: rgba(0, 0, 0, 128);\n"
"padding-left : 20px;\n"
"\n"
"")
        self.LEdit_email_signin.setText("")
        self.LEdit_email_signin.setObjectName("LEdit_email_signin")
        self.verticalLayout_3.addWidget(self.LEdit_email_signin)
        self.label_3 = QtWidgets.QLabel(self.page_1)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color :rgb(255, 255, 255);\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.LEdit_password_signin = QtWidgets.QLineEdit(self.page_1)
        self.LEdit_password_signin.setMinimumSize(QtCore.QSize(0, 40))
        self.LEdit_password_signin.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px;\n"
"color: rgba(0, 0, 0, 128);\n"
"padding-left : 20px;\n"
"")
        self.LEdit_password_signin.setText("")
        self.LEdit_password_signin.setObjectName("LEdit_password_signin")
        self.verticalLayout_3.addWidget(self.LEdit_password_signin)
        self.label_10 = QtWidgets.QLabel(self.page_1)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("padding-left : 10px;\n"
"color: rgb(255, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.btn_signIn = QtWidgets.QPushButton(self.page_1)
        self.btn_signIn.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_signIn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_signIn.setFont(font)
        self.btn_signIn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_signIn.setStyleSheet("#btn_signIn{background-color: rgb(0, 0, 112);\n"
"border-radius : 10px;\n"
"color :rgb(255, 255, 255);}\n"
"#btn_signIn:hover{\n"
"background-color : rgb(0, 85, 127)\n"
"}")
        self.btn_signIn.setObjectName("btn_signIn")
        self.verticalLayout_3.addWidget(self.btn_signIn)
        self.widget_5 = QtWidgets.QWidget(self.page_1)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color :rgb(255, 255, 255);\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.btn_change_page = QtWidgets.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_change_page.setFont(font)
        self.btn_change_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_change_page.setStyleSheet("color :rgb(255, 255, 255);\n"
"")
        self.btn_change_page.setObjectName("btn_change_page")
        self.horizontalLayout_2.addWidget(self.btn_change_page)
        self.verticalLayout_3.addWidget(self.widget_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 50))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color :rgb(255, 255, 255);\n"
"")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.LEdit_email_register = QtWidgets.QLineEdit(self.page_2)
        self.LEdit_email_register.setMinimumSize(QtCore.QSize(0, 40))
        self.LEdit_email_register.setMaximumSize(QtCore.QSize(16777215, 40))
        self.LEdit_email_register.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px ;\n"
"color: rgba(0, 0, 0, 128);\n"
"padding-left : 20px;\n"
"")
        self.LEdit_email_register.setText("")
        self.LEdit_email_register.setObjectName("LEdit_email_register")
        self.verticalLayout_4.addWidget(self.LEdit_email_register)
        self.label_11 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("padding-left : 10px;\n"
"color: rgb(255, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color :rgb(255, 255, 255);\n"
"")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.LEdit_password_register = QtWidgets.QLineEdit(self.page_2)
        self.LEdit_password_register.setMinimumSize(QtCore.QSize(0, 40))
        self.LEdit_password_register.setMaximumSize(QtCore.QSize(16777215, 40))
        self.LEdit_password_register.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px ;\n"
"color: rgba(0, 0, 0, 128);\n"
"padding-left : 20px;\n"
"LEdit_password_register.setEchoMode(Password)\n"
"\n"
"")
        self.LEdit_password_register.setText("")
        self.LEdit_password_register.setObjectName("LEdit_password_register")
        self.verticalLayout_4.addWidget(self.LEdit_password_register)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color :rgb(255, 255, 255);\n"
"")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.LEdit_confirm = QtWidgets.QLineEdit(self.page_2)
        self.LEdit_confirm.setMinimumSize(QtCore.QSize(0, 40))
        self.LEdit_confirm.setMaximumSize(QtCore.QSize(16777215, 40))
        self.LEdit_confirm.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px ;\n"
"color: rgba(0, 0, 0, 128);\n"
"padding-left : 20px;\n"
"\n"
"")
        self.LEdit_confirm.setText("")
        self.LEdit_confirm.setObjectName("LEdit_confirm")
        self.verticalLayout_4.addWidget(self.LEdit_confirm)
        self.label_12 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("padding-left : 10px;\n"
"color: rgb(255, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color :rgb(255, 255, 255);\n"
"")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.LEdit_phone = QtWidgets.QLineEdit(self.page_2)
        self.LEdit_phone.setMinimumSize(QtCore.QSize(0, 40))
        self.LEdit_phone.setMaximumSize(QtCore.QSize(16777215, 40))
        self.LEdit_phone.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 10px ;\n"
"color: rgba(0, 0, 0, 128);\n"
"padding-left : 20px;\n"
"\n"
"")
        self.LEdit_phone.setText("")
        self.LEdit_phone.setObjectName("LEdit_phone")
        self.verticalLayout_4.addWidget(self.LEdit_phone)
        self.btn_register = QtWidgets.QPushButton(self.page_2)
        self.btn_register.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_register.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register.setFont(font)
        self.btn_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_register.setStyleSheet("#btn_register{background-color: rgb(0, 0, 112);\n"
"border-radius : 10px;\n"
"color :rgb(255, 255, 255);}\n"
"#btn_register:hover{\n"
"background-color:rgb(0, 0, 59)\n"
"}")
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout_4.addWidget(self.btn_register)
        self.btn_login = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setStyleSheet("#btn_login{color:rgb(255, 255, 255);\n"
"border-radius : 10px;\n"
"}\n"
"")
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_4.addWidget(self.btn_login)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        spacerItem2 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_4.setStyleSheet("￼")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.LEdit_email_signin.setPlaceholderText(_translate("MainWindow", "username"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.LEdit_password_signin.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_10.setText(_translate("MainWindow", "Error"))
        self.btn_signIn.setText(_translate("MainWindow", "Sign In"))
        self.label_4.setText(_translate("MainWindow", "Don\'t have an account yet?"))
        self.btn_change_page.setText(_translate("MainWindow", "Register for free"))
        self.label_5.setText(_translate("MainWindow", "Register"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.LEdit_email_register.setPlaceholderText(_translate("MainWindow", "Username@gmail.com"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "Password"))
        self.LEdit_password_register.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_8.setText(_translate("MainWindow", "Confirm Password"))
        self.LEdit_confirm.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "Phone Number"))
        self.LEdit_phone.setPlaceholderText(_translate("MainWindow", "Phone Number"))
        self.btn_register.setText(_translate("MainWindow", "Register"))
        self.btn_login.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
