# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\manager_row.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1013, 94)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget__ = QtWidgets.QWidget(Form)
        self.widget__.setObjectName("widget__")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget__)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label__33 = QtWidgets.QLabel(self.widget__)
        self.label__33.setAlignment(QtCore.Qt.AlignCenter)
        self.label__33.setObjectName("label__33")
        self.horizontalLayout_22.addWidget(self.label__33)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.label__1 = QtWidgets.QLabel(self.widget__)
        self.label__1.setMinimumSize(QtCore.QSize(54, 50))
        self.label__1.setMaximumSize(QtCore.QSize(54, 50))
        self.label__1.setStyleSheet("border-radius : 15px;\n"
"margin-left: 2px;\n"
"margin-left: 2px;")
        self.label__1.setText("")
        self.label__1.setPixmap(QtGui.QPixmap(".\\Image/z5461290588979_692bf1a21a79b202b016a475ef95d80d.jpg"))
        self.label__1.setScaledContents(True)
        self.label__1.setAlignment(QtCore.Qt.AlignCenter)
        self.label__1.setObjectName("label__1")
        self.horizontalLayout_22.addWidget(self.label__1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.label__44 = QtWidgets.QLabel(self.widget__)
        self.label__44.setAlignment(QtCore.Qt.AlignCenter)
        self.label__44.setObjectName("label__44")
        self.horizontalLayout_22.addWidget(self.label__44)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.label__2 = QtWidgets.QLabel(self.widget__)
        self.label__2.setAlignment(QtCore.Qt.AlignCenter)
        self.label__2.setObjectName("label__2")
        self.horizontalLayout_22.addWidget(self.label__2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.label__5 = QtWidgets.QLabel(self.widget__)
        self.label__5.setAlignment(QtCore.Qt.AlignCenter)
        self.label__5.setObjectName("label__5")
        self.horizontalLayout_22.addWidget(self.label__5)
        spacerItem4 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.widget__2 = QtWidgets.QWidget(self.widget__)
        self.widget__2.setObjectName("widget__2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget__2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton__ = QtWidgets.QPushButton(self.widget__2)
        self.pushButton__.setMinimumSize(QtCore.QSize(42, 0))
        self.pushButton__.setMaximumSize(QtCore.QSize(41, 44))
        self.pushButton__.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton__.setStyleSheet("#pushButton__{\n"
"border-radius : 15px;\n"
"border-right : none\n"
"\n"
"}\n"
"#pushButton__:hover {\n"
"                background-color: rgb(255,0,0); \n"
"            }")
        self.pushButton__.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Image/icons8-delete-trash-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__.setIcon(icon)
        self.pushButton__.setObjectName("pushButton__")
        self.horizontalLayout_2.addWidget(self.pushButton__)
        self.horizontalLayout_22.addWidget(self.widget__2)
        self.horizontalLayout.addWidget(self.widget__)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label__33.setText(_translate("Form", "1"))
        self.label__44.setText(_translate("Form", "Pham Doan Minh Hieu"))
        self.label__2.setText(_translate("Form", "abc@gmail.com"))
        self.label__5.setText(_translate("Form", "0762649422"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
