# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file '.\row_rank.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
current_directory = os.path.dirname(os.path.abspath(__file__)) + '\\'


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 94)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget____ = QtWidgets.QWidget(Form)
        self.widget____.setObjectName("widget____")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget____)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label___33 = QtWidgets.QLabel(self.widget____)
        self.label___33.setAlignment(QtCore.Qt.AlignCenter)
        self.label___33.setObjectName("label___33")
        self.horizontalLayout_22.addWidget(self.label___33)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.label___5 = QtWidgets.QLabel(self.widget____)
        self.label___5.setMinimumSize(QtCore.QSize(30, 20))
        self.label___5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label___5.setText("")
        self.label___5.setPixmap(QtGui.QPixmap(current_directory + ".\\Image/image 2.png"))
        self.label___5.setScaledContents(True)
        self.label___5.setAlignment(QtCore.Qt.AlignCenter)
        self.label___5.setObjectName("label___5")
        self.horizontalLayout_22.addWidget(self.label___5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.label___1 = QtWidgets.QLabel(self.widget____)
        self.label___1.setMinimumSize(QtCore.QSize(54, 50))
        self.label___1.setMaximumSize(QtCore.QSize(54, 50))
        self.label___1.setStyleSheet("border-radius : 15px;\n"
"margin-left: 2px;\n"
"margin-left: 2px;")
        self.label___1.setText("")
        self.label___1.setPixmap(QtGui.QPixmap(current_directory + ".\\Image/Ellipse 10.png"))
        self.label___1.setScaledContents(True)
        self.label___1.setAlignment(QtCore.Qt.AlignCenter)
        self.label___1.setObjectName("label___1")
        self.horizontalLayout_22.addWidget(self.label___1)
        spacerItem2 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.label___44 = QtWidgets.QLabel(self.widget____)
        self.label___44.setAlignment(QtCore.Qt.AlignCenter)
        self.label___44.setObjectName("label___44")
        self.horizontalLayout_22.addWidget(self.label___44)
        spacerItem3 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.label___2 = QtWidgets.QLabel(self.widget____)
        self.label___2.setAlignment(QtCore.Qt.AlignCenter)
        self.label___2.setObjectName("label___2")
        self.horizontalLayout_22.addWidget(self.label___2)
        self.horizontalLayout.addWidget(self.widget____)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label___33.setText(_translate("Form", "1"))
        self.label___44.setText(_translate("Form", "Pham Doan Minh Hieu"))
        self.label___2.setText(_translate("Form", "100"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
