# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1010, 84)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget__ = QtWidgets.QWidget(Form)
        self.widget__.setObjectName("widget__")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget__)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label__ID = QtWidgets.QLabel(self.widget__)
        self.label__ID.setAlignment(QtCore.Qt.AlignCenter)
        self.label__ID.setObjectName("label__ID")
        self.horizontalLayout_22.addWidget(self.label__ID)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.label__word = QtWidgets.QLabel(self.widget__)
        self.label__word.setAlignment(QtCore.Qt.AlignCenter)
        self.label__word.setObjectName("label__word")
        self.horizontalLayout_22.addWidget(self.label__word)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.label__score = QtWidgets.QLabel(self.widget__)
        self.label__score.setAlignment(QtCore.Qt.AlignCenter)
        self.label__score.setObjectName("label__score")
        self.horizontalLayout_22.addWidget(self.label__score)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.label__learned = QtWidgets.QLabel(self.widget__)
        self.label__learned.setAlignment(QtCore.Qt.AlignCenter)
        self.label__learned.setObjectName("label__learned")
        self.horizontalLayout_22.addWidget(self.label__learned)
        self.horizontalLayout.addWidget(self.widget__)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label__ID.setText(_translate("Form", "1"))
        self.label__word.setText(_translate("Form", "Thanks"))
        self.label__score.setText(_translate("Form", "100"))
        self.label__learned.setText(_translate("Form", "Learned"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
