# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QListWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget__40 = QtWidgets.QWidget(self.centralwidget)
        self.widget__40.setObjectName("widget__40")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget__40)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label__3 = QtWidgets.QLabel(self.widget__40)
        self.label__3.setAlignment(QtCore.Qt.AlignCenter)
        self.label__3.setObjectName("label__3")
        self.horizontalLayout_22.addWidget(self.label__3)
        self.label__ = QtWidgets.QLabel(self.widget__40)
        self.label__.setText("")
        self.label__.setAlignment(QtCore.Qt.AlignCenter)
        self.label__.setObjectName("label__")
        self.horizontalLayout_22.addWidget(self.label__)
        self.label__4 = QtWidgets.QLabel(self.widget__40)
        self.label__4.setAlignment(QtCore.Qt.AlignCenter)
        self.label__4.setObjectName("label__4")
        self.horizontalLayout_22.addWidget(self.label__4)
        self.label__13 = QtWidgets.QLabel(self.widget__40)
        self.label__13.setAlignment(QtCore.Qt.AlignCenter)
        self.label__13.setObjectName("label__13")
        self.horizontalLayout_22.addWidget(self.label__13)
        self.label__14 = QtWidgets.QLabel(self.widget__40)
        self.label__14.setAlignment(QtCore.Qt.AlignCenter)
        self.label__14.setObjectName("label__14")
        self.horizontalLayout_22.addWidget(self.label__14)
        self.label__16 = QtWidgets.QLabel(self.widget__40)
        self.label__16.setText("")
        self.label__16.setAlignment(QtCore.Qt.AlignCenter)
        self.label__16.setObjectName("label__16")
        self.horizontalLayout_22.addWidget(self.label__16)
        self.horizontalLayout.addWidget(self.widget__40)
        self.newItem = QListWidgetItem()
        self.newItem.setSizeHint(QSize(1, 150))
        self.listWidget_2.addItem(self.newItem)
        self.listWidget_2.setItemWidget(self.newItem, self.widget__40)
        self.newItem = QListWidgetItem()
        self.newItem.setSizeHint(QSize(1, 150))
        self.listWidget_2.addItem(self.newItem)
        self.listWidget_2.setItemWidget(self.newItem, self.ư)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label__3.setText(_translate("MainWindow", "ID"))
        self.label__4.setText(_translate("MainWindow", "Name"))
        self.label__13.setText(_translate("MainWindow", "Email"))
        self.label__14.setText(_translate("MainWindow", "Phone Number"))
