from enum import Enum


class Command(Enum):
    USER = -1
    USERNAME_AND_PASSWORD = -2
    SEND_SERVER_REGISTER = -3
    SEND_CLIENT_REGISTER = -4
    SEND_SERVER_EDIT = -5
    SEND_CLIENT_EDIT = -6
    SEND_CHANGE_PASSWORD = -7
    SEND_SERVER_DELETE = -8
    SEND_SERVER_GET_LIST_USER = -9
    SEND_CLIENT_GET_LIST_USER = -10
    SEND_CLIENT_AFTER_DELETE = -11
    SEND_SERVER_LIST_RANK = -12
    SEND_CLIENT_LIST_RANK = -13
